pipeline {
    agent any
    tools {
        maven 'Maven' 
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Test') {
            steps {
                dir('student-management') {
                    bat 'mvn clean package'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('student-management') {
                    bat 'docker build -t student-management-app .'
                }
            }
        }
        stage('Docker Deploy') {
            steps {
                bat 'docker rm -f student-app-pipeline || exit 0'
                bat 'docker run -d -p 8082:8080 --name student-app-pipeline student-management-app'
            }
        }
    }
}
